### ISSUE TITLE
DB problems when stop/starting the CHe

### ISSUE THREAD

**Issue by Alfiva** [universAAL/context#12]
_Originally Opened: @Alfiva (2011-03-16 13:06:30_)
_Originally Closed: 2013-09-18 19:28:06_

When the CHe is stopped and then it is started again there is a DB error message when trying to store new events, although apparently they are stored.

--

From: _this issue has been automatically imported from our old issue tracker_

**Comment by Alfiva** [comment]
_Original author: @Alfiva (2011-11-22 18:53:46)_

With the new version of CHe based on Sesame no DB is used anymore. However this is still a problem, since this new version uses MW 0.3.1: Now when the bundle *is restarted* everything seems to work fine (and it does, the events are stored and services work) but the following error appears whenever an event arrives:

Exception in thread &quot;Thread-15&quot; java.lang.IllegalStateException: Invalid BundleContext.
	at org.apache.felix.framework.BundleContextImpl.checkValidity(BundleContextImpl.java:457)
	at org.apache.felix.framework.BundleContextImpl.getBundle(BundleContextImpl.java:97)
	at org.universAAL.middleware.container.osgi.uAALBundleContext.getID(uAALBundleContext.java:118)
	at org.universAAL.middleware.container.utils.LogUtils.log(LogUtils.java:89)
	at org.universAAL.middleware.container.utils.LogUtils.logInfo(LogUtils.java:199)
	at org.universAAL.middleware.context.ContextSubscriber.handleEvent(ContextSubscriber.java:129)
	at org.universAAL.middleware.context.impl.ContextStrategy.handle(ContextStrategy.java:296)
	at org.universAAL.middleware.sodapop.BusStrategy$HandlerThread.run(BusStrategy.java:50)

**Comment by Alfiva** [comment]
_Original author: @Alfiva (2013-09-18 19:28:05)_

It´s prior to MW 2.0. No longer applies.

**Comment by Alfiva** [comment]
issue cloed on 2013-09-18 19:28:06
