### ISSUE TITLE
An unknown exception occured while registering ReasoningOntology  

### ISSUE THREAD

**Issue by Alfiva** [universAAL/context#304]
_Originally Opened: @geibsan (2013-06-05 18:42:27_)
_Originally Closed: 2013-09-18 15:02:44_

I am working in Nutritional Advisor service in Eclipse. I am using ont.composite and mw.composite 1.3.3-SNAPSHOT version. When starting the platform I get the following error:

DEBUG: WIRE: [50.0] package; (package=org.universAAL.middleware.service.owl) -&gt; [85.0]
mw.container.osgi[org.universAAL.mw.data.representation.osgi] : OntologyManagement-&gt;register(): Registering ontology: http://reasoner.universAAL.org/ReasoningOntology
mw.container.osgi[org.universAAL.mw.data.representation.osgi] : OntologyManagement-&gt;register_testClass(): An unknown exception occured while testing the ontology class http://reasoner.universAAL.org/ReasoningOntology#Rule during registration of the ontology http://reasoner.universAAL.org/ReasoningOntology.
java.lang.NullPointerException
	at org.universAAL.middleware.owl.ManagedIndividual.setProperty(ManagedIndividual.java:431)
	at org.universAAL.middleware.rdf.Resource.changeProperty(Resource.java:421)
	at org.universAAL.reasoner.ont.Persistent.setPersistent(Persistent.java:67)
	at org.universAAL.reasoner.ont.Persistent.&lt;init&gt;(Persistent.java:37)
	at org.universAAL.reasoner.ont.Rule.&lt;init&gt;(Rule.java:34)
	at org.universAAL.reasoner.ont.factory.OntFactory.createInstance(OntFactory.java:41)
	at org.universAAL.middleware.owl.OntologyManagement.register_testClass(OntologyManagement.java:306)
	at org.universAAL.middleware.owl.OntologyManagement.register(OntologyManagement.java:469)
	at org.universAAL.reasoner.ont.osgi.Activator.start(Activator.java:46)
	at org.universAAL.middleware.container.osgi.run.uAALBundleExtender$ActivatorExecutor.start(uAALBundleExtender.java:194)
	at org.universAAL.middleware.container.osgi.run.uAALBundleExtender.doStart(uAALBundleExtender.java:104)
	at org.universAAL.middleware.container.osgi.run.uAALBundleExtender.bundleChanged(uAALBundleExtender.java:145)
	at org.apache.felix.framework.util.EventDispatcher.invokeBundleListenerCallback(EventDispatcher.java:800)
	at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:728)
	at org.apache.felix.framework.util.EventDispatcher.fireBundleEvent(EventDispatcher.java:610)
	at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:3715)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:1762)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1143)
	at org.apache.felix.framework.StartLevelImpl.run(StartLevelImpl.java:264)
	at java.lang.Thread.run(Thread.java:662)

--

From: _this issue has been automatically imported from our old issue tracker_

**Comment by Alfiva** [comment]
_Original author: @Alfiva (2013-09-18 15:02:44)_

No longer seems to happen with MW 2.0

**Comment by Alfiva** [comment]
issue cloed on 2013-09-18 15:02:44
