### ISSUE TITLE
CHE causes JVM Heap memory overflow by too many blocked threads waiting for monitor entery of SesameBackend.storeEvent

### ISSUE THREAD

**Issue by Alfiva** [universAAL/context#474]
_Originally Opened: @saiedt (2015-09-01 17:32:11_)
_Originally Closed: 2016-08-03 13:51:45_

Problem occurred: JVM Heap memory overflow

Configuration: all AAL Space components running in a centralized way in one Karaf instance within a Linux VM

Effect in a dump file created ca. one hour after restarting Karaf on the same VM: found over 9000 blocked threads similar to the following:

&quot;Context Bus Strategy Handler&quot; daemon prio=10 tid=0x00007f5d38011800 nid=0x6734 waiting for monitor entry [0x00007f5d10710000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org...che.database.impl.SesameBackend.storeEvent(SesameBackend.java:253)
	- waiting to lock &lt;0x00000000f93f0c28&gt; (a org...che.database.impl.SesameBackend)
	at org...che.ContextHistorySubscriber.handleContextEvent(ContextHistorySubscriber.java:92)

   Locked ownable synchronizers:
	- None

Checked size of CHE DB on disk: &gt; 10GB

RECYCLE.KEEP property of CHE already set to 1

Workaround: AAL Space is running without CHE until the problem is solved

--

From: _this issue has been automatically imported from our old issue tracker_

**Comment by Alfiva** [comment]
_Original author: @Alfiva (2015-09-02 10:42:30)_

I need some additional data: the configuration file CHE.properties and a log file that includes CHE DEBUG log messages when running on that problematic instance (no need to be of the exact time when it fails, just normal operation in  that 10GB instance you mention, while storing some events)

**Comment by Alfiva** [comment]
_Original author: @Alfiva (2015-09-02 11:39:51)_

If the exception shown is right, then the problem could be while opening the connection to the store, not when actually storing the event. The log I requested before could also help identifying this problem, since the elapsed time for storing the event would always be low, indicating that the delay is outside, when opening the connection.

If this was the cause, I could try to fix this by having a singleton connection to the store always open. Right now the CHE open/closes the connection everytime there is an event. This was made thinking about saving resources in spaces with &quot;sparse&quot; events. But if the opening of the connection takes increasingly longer to perform, it may be worth the tradeoff of having it always open.

I could create a branch with this fix that you could use for testing, but first I would like to see the logs so I can confirm this.

**Comment by Alfiva** [comment]
_Original author: @HelmiBH (2015-09-02 11:58:59)_

Yes, please wait till 100% identifying the problem...IPlease find the Log here https://cloud.igd.fraunhofer.de/owncloud/public.php?service=files&amp;t=17905c2b4727f0de8023743a82f45c62

As you said, we have also tested again with a full (10GO) che and a clean one=&gt; Same result: the instance with a full heap was killed in 15 min... 

Now we are testing with 2 instances: 1 with an emtpy CHE and a second one without CHE, both have a very small heap (64 MB). till now both are still working (2 days now), with a very normal behaviour (same number of threads)...

I ll keep you in touch in case I have news

Helmi

**Comment by Alfiva** [comment]
_Original author: @HelmiBH (2015-09-02 13:17:21)_

I have included the Log file from one app under the same link in my above message. As we have restarted all Vms, I don´t know if the &quot;old&quot; Log will be ereased or not...

**Comment by Alfiva** [comment]
_Original author: @Alfiva (2015-09-03 11:57:26)_

Created the &quot;Fix-747&quot; branch at the context repo. Please use that and compile che and che.module.cardinality. Try those and report back.

**Comment by Alfiva** [comment]
_Original author: @Alfiva (2015-10-26 10:32:00)_

This &quot;fix&quot; was already included in release 3.4.0 since there was no feedback about its validity - and did not introduce any error to normal operation.
I am awaiting results to see if it actually fixed the issue.

**Comment by Alfiva** [comment]
_Original author: @HelmiBH (2015-10-26 11:05:02)_

We will start new depl based on the MW today. Will come to you with a clear statement in 1 week!

Best
Helmi

**Comment by Alfiva** [comment]
_Original author: @Alfiva (2016-08-03 13:51:45)_

No further feedback. Closing.

**Comment by Alfiva** [comment]
issue cloed on 2016-08-03 13:51:45
